name: "Nix Build & Check"
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/nix.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check flake metadata
        run: nix flake check

      - name: Build project
        run: nix build .